## Basic numpy arrays

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## 2D & 3D Numpy arrays

In [3]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(f"Printing 2x3 matrix: \n {arr1}")
print(f"\nPrinting 3x3 matrix:\n{arr2}")

Printing 2x3 matrix: 
 [[1 2 3]
 [4 5 6]]

Printing 3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Dimensions of a Numpy Array

In [4]:
print(f"No. of Dimensions of 2x3 matrix is: {arr1.ndim}")
print(f"No. of Dimensions of 3x3 matrix is: {arr2.ndim}")

No. of Dimensions of 2x3 matrix is: 2
No. of Dimensions of 3x3 matrix is: 2


## Accessing Indivisual elements from an array ( Indexing )

In [13]:
print(f"Printing the 1D array: \n{arr}")
print(f"Printing the value of the 2nd index of the 1D array: {arr[2]}")
print(f"\nThis is the 3x3 matrix array: \n{arr2}")
print(f"Printing the value of the 0th Row and the 2nd Column of the 3x3 matrix: {arr2[0][2]}")

Printing the 1D array: 
[1 2 3 4 5]
Printing the value of the 2nd index of the 1D array: 3

This is the 3x3 matrix array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Printing the value of the 0th Row and the 2nd Column of the 3x3 matrix: 3


## Slicing elements in Numpy array

In [15]:
print(f"Slicing the 1D array: {arr[:4]}\n")
print(f"Slicing the 1D array after an index: {arr[1:4]}\n")
print(f"This is the 3x3 matrix array: \n{arr2}")
print(f"\nSlicing the 3x3 matrix: \n{arr2[1,1:3]}")
print(f"\nSlicing the 3x3 matrix: \n{arr2[1:3,1:3]}")


Slicing the 1D array: [1 2 3 4]

Slicing the 1D array after an index: [2 3 4]

This is the 3x3 matrix array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Slicing the 3x3 matrix: 
[5 6]

Slicing the 3x3 matrix: 
[[5 6]
 [8 9]]
